import numpy as np

# get estimated time of running the task on the node
def estimate_runtime(task, node):
    return task.runtime / np.log(node.cores + 1)


# estimate transfer time between node1 and node2 for data generated by the task
def estimate_transfer_time(node1, node2, task1, task2):
    transfer_speed = 50 * 1024 * 1024
    if node1 == node2:
        return 0.0
    else:
        vol = volume_to_transfer(task1, task2)
        return vol / transfer_speed


def volume_to_transfer(task1, task2):
    input = task1.input_files
    output = task2.output_files
    req_files = input.keys() & output.keys()
    volume = sum([input[f].size for f in list(req_files)])
    return volume
